// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values if env vars are not set
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://oyjxzrvhvndbdoyshwfc.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95anh6cnZodm5kYmRveXNod2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0MjI5MDUsImV4cCI6MjA4MTk5ODkwNX0._N7H-ovxKGqDAZTog9FuZw_AEdZjPqqqqCXxBGn2VEs';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

